version: '3.8'

networks:
  go-routine-network:
    name: go-routine-network
    driver: bridge

services:
  player-service:
    build:
      context: ./player-service
      dockerfile: dockerfile
    ports:
      - "8888:8888"  
    networks:
      - go-routine-network
    depends_on:
      - mongoDB
    environment:
      MONGO_URI: mongodb://root:example@mongoDB:27017/mydb?authSource=admin
      TABLE_URI: table-service:8889

  table-service:
    build:
      context: ./table-service
      dockerfile: dockerfile
    ports:
      - "8889:8889" 
    networks:
      - go-routine-network

  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - "27017:27017"
    networks:
      - go-routine-network
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data:
    driver: local
