version: '3.8'

networks:
  go-routine-network:
    name: go-routine-network
    driver: bridge

services:
  player-service:
    build:
      context: ./player-service
      dockerfile: dockerfile
    ports:
      - "8888:8888"  
    networks:
      - go-routine-network

  table-service:
    build:
      context: ./table-service
      dockerfile: dockerfile
    ports:
      - "8889:8889" 
    networks:
      - go-routine-network
