apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
        - name: player-service
          image: {{ .Values.playerService.image }}
          ports:
            - containerPort: {{ .Values.playerService.port }}
          env:
            - name: MONGO_URI
              value: {{ .Values.playerService.mongoUri }}
