apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table-service
  template:
    metadata:
      labels:
        app: table-service
    spec:
      containers:
        - name: table-service
          image: {{ .Values.tableService.image }}
          ports:
            - containerPort: {{ .Values.tableService.port }}
