apiVersion: v1
kind: Service
metadata:
  name: table-service
spec:
  selector:
    app: table-service
  ports:
    - protocol: TCP
      port: {{ .Values.tableService.port }}
      targetPort: {{ .Values.tableService.port }}
  type: ClusterIP
