apiVersion: v1
kind: Service
metadata:
  name: player-service
spec:
  selector:
    app: player-service
  ports:
    - protocol: TCP
      port: {{ .Values.playerService.port }}
      targetPort: {{ .Values.playerService.port }}
  type: ClusterIP
