# Dockerfile for table-service
FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o table-service main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/table-service .
EXPOSE 8889  
# Expose port 8889

CMD ["./table-service"]
