apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
      - name: player-service
        image: fxank/player-service:latest
        ports:
        - containerPort: 8888
        env:
            - name: MONGO_URI
              value: "mongodb://root:example@mongodb.default.svc.cluster.local:27017/mydb?authSource=admin"

---
apiVersion: v1
kind: Service
metadata:
  name: player-service
spec:
  selector:
    app: player-service
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP