mongodb:
  image: "mongo:latest"
  username: "root"
  password: "example"
  database: "mydb"
  storage: 
    size: "5Gi"
  
playerService:
  image: "fxank/player-service:latest"
  port: 8888
  mongoUri: "mongodb://root:example@mongodb:27017/mydb?authSource=admin"

tableService:
  image: "fxank/table-service:latest"
  port: 8889
