# values.yaml

# Global network details (not directly needed in Kubernetes)
network: go-routine-network

playerService:
  replicas: 1
  image:
    repository: fxank/player-service
    tag: latest
  port: 8888

tableService:
  replicas: 1
  image:
    repository: fxank/table-service
    tag: latest
  port: 8889
