apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
        - name: player-service
          image: fxank/player-service:latest
          env:
            - name: MONGO_URI
              value: mongodb://root:example@localhost:27017/mydb?authSource=admin # MongoDB connection string
          ports:
            - containerPort: 8888



